import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Stream;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        example1();
        example2();
        example3();
        example4();
        example5();
        example6();
    }
    
    static void example1() {
    	List<Integer>list1 = new ArrayList<>();
    	list1.add(1);
    	list1.add(5);
    	list1.add(3);
    	
    	// Convert it into a Stream
    	Stream<Integer> newStrem=list1.stream();
    	//System.out.println(" " + list1 );
    	
    	// Print the contents of the stream
    	newStrem.forEach(e -> System.out.println(e));
    }
    static void example2() {
    	
    	Integer[] myArray = {1,8,7};
    	
    	// Convert it into a Stream
    	Stream<Integer> myStream = Arrays.stream(myArray);
    	
    	
    	// Print the contents of the stream
	    myStream.forEach(e -> System.out.println(e));
    }
    
    // using map method
    static void example3() {
		String[] myArray = new String[]{"bob", "alice", "paul", "ellie"};
		Stream<String> myStream =  Arrays.stream(myArray);
		
		Stream<String> myNewStream =myStream.map(s -> s.toUpperCase());
		
		String[] myNewArray =
	             myNewStream.toArray(String[]::new);
		
		// Print the contents of the new array		
				for(String s:myNewArray)
					System.out.println(s);
    }
    //using filter method
    static void example4() {
		String[] myArray = new String[]{"bob", "alice", "paul", "ellie"};
		Stream<String> myStream  = Arrays.stream(myArray);
         
		Stream<String> myNewStream = myStream.filter(s -> s.length()>4);
		String[] myNewArray = myNewStream.toArray(String[]::new);
		

		// Print the contents of the new array		
				for(String a:myNewArray)
					System.out.println(a);
    }
    
   // reduction operation
	static void example5() {
		int myArray[] = { 1, 5, 8 };
		int sum = Arrays.stream(myArray).sum();

        	// Print the sum
		System.out.println(sum);
	}
	
	static void example6() {
		String[] myArray = { "this", "is", "a", "sentence" };
		String result = Arrays.stream(myArray).reduce("",(a,b)-> a + b);
		
		System.out.println(result);
	}
}
